package com.saenz.myprj
data class Level_1(var title: String, var img: Int)

object Supplier {

    val animals = listOf(
        Level_1("bee",R.drawable.bee),
        Level_1("boar",R.drawable.boar),
        Level_1("cat",R.drawable.cat),
        Level_1("cow",R.drawable.cow),
        Level_1("dog",R.drawable.dog),
        Level_1("duck",R.drawable.duck),
        Level_1("elephant",R.drawable.elephant),
        Level_1("frog",R.drawable.frog),
        Level_1("goat",R.drawable.goat),
        Level_1("hen",R.drawable.hen),
        Level_1("horse",R.drawable.horse),
        Level_1("parrot",R.drawable.parrot),
        Level_1("sheep",R.drawable.sheep),
        Level_1("wolf",R.drawable.wolf),
        Level_1("bee",R.drawable.bee),
        Level_1("boar",R.drawable.boar),
        Level_1("cat",R.drawable.cat),
        Level_1("cow",R.drawable.cow),
        Level_1("dog",R.drawable.dog),
        Level_1("duck",R.drawable.duck),
        Level_1("elephant",R.drawable.elephant),
        Level_1("frog",R.drawable.frog),
        Level_1("goat",R.drawable.goat),
        Level_1("hen",R.drawable.hen),
        Level_1("horse",R.drawable.horse),
        Level_1("parrot",R.drawable.parrot),
        Level_1("sheep",R.drawable.sheep),
        Level_1("wolf",R.drawable.wolf)
    )

    val personas = listOf(
        Level_1("goat",R.drawable.goat),
        Level_1("hen",R.drawable.hen),
        Level_1("horse",R.drawable.horse),

        Level_1("cat",R.drawable.cat),
        Level_1("cow",R.drawable.cow),
        Level_1("dog",R.drawable.dog),
        Level_1("duck",R.drawable.duck),
        Level_1("elephant",R.drawable.elephant),

        Level_1("hen",R.drawable.hen),
        Level_1("goat",R.drawable.goat),
        Level_1("hen",R.drawable.hen),

        Level_1("parrot",R.drawable.parrot),
        Level_1("sheep",R.drawable.sheep),
        Level_1("wolf",R.drawable.wolf),
        Level_1("bee",R.drawable.bee),
        Level_1("boar",R.drawable.boar),
        Level_1("cat",R.drawable.cat),
        Level_1("cow",R.drawable.cow),
        Level_1("dog",R.drawable.dog),
        Level_1("duck",R.drawable.duck),
        Level_1("elephant",R.drawable.elephant),
        Level_1("frog",R.drawable.frog),
        Level_1("goat",R.drawable.goat),
        Level_1("hen",R.drawable.hen)
    )

    val objetos = listOf(
        Level_1("sheep",R.drawable.sheep),
        Level_1("wolf",R.drawable.wolf),
        Level_1("bee",R.drawable.bee),
        Level_1("boar",R.drawable.boar),
        Level_1("cat",R.drawable.cat),
        Level_1("cow",R.drawable.cow),
        Level_1("dog",R.drawable.dog),
        Level_1("duck",R.drawable.duck),
        Level_1("elephant",R.drawable.elephant),
        Level_1("frog",R.drawable.frog),
        Level_1("goat",R.drawable.goat),
        Level_1("hen",R.drawable.hen),
        Level_1("goat",R.drawable.goat),
        Level_1("hen",R.drawable.hen),
        Level_1("horse",R.drawable.horse),
        Level_1("parrot",R.drawable.parrot),
        Level_1("sheep",R.drawable.sheep),
        Level_1("wolf",R.drawable.wolf),
        Level_1("bee",R.drawable.bee),
        Level_1("boar",R.drawable.boar),
        Level_1("cat",R.drawable.cat),
        Level_1("cow",R.drawable.cow),
        Level_1("dog",R.drawable.dog),
        Level_1("sheep",R.drawable.sheep),
        Level_1("wolf",R.drawable.wolf),
        Level_1("bee",R.drawable.bee),
        Level_1("boar",R.drawable.boar),
        Level_1("cat",R.drawable.cat),
        Level_1("cow",R.drawable.cow),
        Level_1("dog",R.drawable.dog),
        Level_1("duck",R.drawable.duck),
        Level_1("elephant",R.drawable.elephant),
        Level_1("frog",R.drawable.frog),
        Level_1("goat",R.drawable.goat),
        Level_1("hen",R.drawable.hen),
        Level_1("goat",R.drawable.goat),
        Level_1("hen",R.drawable.hen),
        Level_1("horse",R.drawable.horse),
        Level_1("parrot",R.drawable.parrot),
        Level_1("sheep",R.drawable.sheep),
        Level_1("wolf",R.drawable.wolf),
        Level_1("bee",R.drawable.bee),
        Level_1("boar",R.drawable.boar),
        Level_1("cat",R.drawable.cat),
        Level_1("cow",R.drawable.cow),
        Level_1("dog",R.drawable.dog),
        Level_1("sheep",R.drawable.sheep),
        Level_1("wolf",R.drawable.wolf),
        Level_1("bee",R.drawable.bee),
        Level_1("boar",R.drawable.boar),
        Level_1("cat",R.drawable.cat),
        Level_1("cow",R.drawable.cow),
        Level_1("dog",R.drawable.dog),
        Level_1("duck",R.drawable.duck),
        Level_1("elephant",R.drawable.elephant),
        Level_1("frog",R.drawable.frog),
        Level_1("goat",R.drawable.goat),
        Level_1("hen",R.drawable.hen),
        Level_1("goat",R.drawable.goat),
        Level_1("hen",R.drawable.hen),
        Level_1("horse",R.drawable.horse),
        Level_1("parrot",R.drawable.parrot),
        Level_1("sheep",R.drawable.sheep),
        Level_1("wolf",R.drawable.wolf),
        Level_1("bee",R.drawable.bee),
        Level_1("boar",R.drawable.boar),
        Level_1("cat",R.drawable.cat),
        Level_1("cow",R.drawable.cow),
        Level_1("dog",R.drawable.dog)
    )}